name: hfm-application
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
author: Mingyu Choo
maintainer: mingyuchoo@gmail.com
language: GHC2024
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -O2
when:
- condition: os(darwin)
  ghc-options: -pgml ../../scripts/link-macos.sh
dependencies:
- base >= 4.18 && < 5
- hfm-domain
- text
- bytestring
- filepath
- mtl
- transformers
library:
  source-dirs: src
  exposed-modules:
  - Hfm.Application.Program
  - Hfm.Application.Startup
  - Hfm.Application.Status
  - Hfm.Application.Workflow
  - Hfm.Application.Ports
  - Hfm.Application.State
  - Hfm.Application.UseCases
  other-modules:
  - Hfm.Application.Internal.Action
  - Hfm.Application.Internal.Files
  - Hfm.Application.Internal.Interaction
tests:
  hfm-application-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hfm-application
    - hspec
    - vector
