name:                file-finder
version:             0.1.0.0
github:              mingyuchoo/file-finder
license:             BSD-3-Clause
author:              Mingyu Choo
maintainer:          mingyuchoo@gmail.com
copyright:           Mingyu Choo 2025
synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/file-finder#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.18 && < 5
- containers
- flow
- mtl
- parallel
- text
- optparse-applicative
- directory
- filepath

default-extensions:
- DataKinds
- DeriveGeneric
- ExplicitForAll
- GADTs
- KindSignatures
- StandaloneKindSignatures
- OverloadedStrings
- TypeApplications

ghc-options:
- -Wall
- -O2
- -haddock

language: GHC2024

library:
  source-dirs: src

executables:
  file-finder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-finder

tests:
  file-finder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-finder
    - hspec
    - doctest
    - doctest-discover
    - temporary
