#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
target="$repo_root/docs/generated/route-map.md"
temporary="$(mktemp)"
trap 'rm -f "$temporary"' EXIT

# 원본은 Servant API 타입입니다. 사람이 적은 목록이 아니라 실제 라우트 정의에서 추출합니다.
python3 - "$repo_root" "$temporary" <<'PY'
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
out = Path(sys.argv[2])
source = root / "src/api/src/Todo/Api/Routes.hs"

if not source.exists():
    print(f"라우트 원본이 없습니다: {source}", file=sys.stderr)
    raise SystemExit(1)

lines = source.read_text(encoding="utf-8").splitlines()

# `type TodoApi =` 선언을 들여쓰기가 끝날 때까지 모읍니다.
declaration: list[str] = []
collecting = False
for line in lines:
    if line.startswith("type TodoApi"):
        collecting = True
        declaration.append(line.split("=", 1)[1])
        continue
    if collecting:
        if line.strip() == "" or not line.startswith(" "):
            break
        declaration.append(line)

if not declaration:
    print("type TodoApi 선언을 찾지 못했습니다.", file=sys.stderr)
    raise SystemExit(1)

flat = " ".join(part.strip() for part in declaration)

# 성공 상태 코드는 Servant의 verb 이름이 결정합니다.
VERBS = {
    "Get": ("GET", 200),
    "Post": ("POST", 200),
    "PostCreated": ("POST", 201),
    "PostNoContent": ("POST", 204),
    "Put": ("PUT", 200),
    "PutNoContent": ("PUT", 204),
    "Patch": ("PATCH", 200),
    "PatchNoContent": ("PATCH", 204),
    "Delete": ("DELETE", 200),
    "DeleteNoContent": ("DELETE", 204),
}

rows = []
for alternative in flat.split(":<|>"):
    segments = ["", ]
    segments = []
    queries = []
    verb = None
    for component in alternative.split(":>"):
        component = component.strip()
        literal = re.fullmatch(r'"([^"]+)"', component)
        if literal:
            segments.append(literal.group(1))
            continue
        capture = re.match(r'Capture\s+"([^"]+)"', component)
        if capture:
            segments.append("{" + capture.group(1) + "}")
            continue
        query = re.match(r'QueryParams?\s+"([^"]+)"', component)
        if query:
            queries.append(query.group(1))
            continue
        head = component.split()[0] if component.split() else ""
        if head in VERBS:
            verb = VERBS[head]
    if verb is None:
        continue
    method, status = verb
    path = "/" + "/".join(segments)
    rows.append((method, path, ", ".join(queries) if queries else "없음", status))

if not rows:
    print("라우트를 하나도 추출하지 못했습니다.", file=sys.stderr)
    raise SystemExit(1)

table = "\n".join(f"| {method} | `{path}` | {query} | {status} |" for method, path, query, status in rows)

out.write_text(
    "# Route Map\n"
    "\n"
    "<!-- AUTOGENERATED: scripts/context/generate-route-map.sh -->\n"
    "\n"
    "원본: `src/api/src/Todo/Api/Routes.hs`\n"
    "\n"
    "| 메서드 | 경로 | 질의 매개변수 | 성공 상태 |\n"
    "|---|---|---|---|\n"
    f"{table}\n"
    "\n"
    "요청과 응답의 의미, 오류 모델과 호환성 정책은 `docs/contracts/api/TODO-API-v1.md`에 있습니다.\n"
    "이 파일을 직접 수정하지 마십시오.\n",
    encoding="utf-8",
)
PY

if [[ "${1:-}" == "--check" ]]; then
  if ! cmp -s "$temporary" "$target"; then
    printf '생성 문서가 오래되었습니다: %s\n' "$target" >&2
    exit 1
  fi
  printf '라우트 지도 최신 상태 확인\n'
else
  cp "$temporary" "$target"
  printf '생성 완료: %s\n' "$target"
fi
