#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
dependency_target="$repo_root/docs/generated/dependency-graph.md"
service_target="$repo_root/docs/generated/service-map.md"
dependency_temporary="$(mktemp)"
service_temporary="$(mktemp)"
trap 'rm -f "$dependency_temporary" "$service_temporary"' EXIT

# 원본은 각 패키지의 cabal 파일입니다. 문서가 아니라 빌드 설정이 사실의 근거입니다.
python3 - "$repo_root" "$dependency_temporary" "$service_temporary" <<'PY'
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
dependency_out = Path(sys.argv[2])
service_out = Path(sys.argv[3])

cabal_files = sorted((root / "src").glob("*/*.cabal"))
if not cabal_files:
    print("src 아래에서 cabal 파일을 찾지 못했습니다.", file=sys.stderr)
    raise SystemExit(1)


def field(text: str, name: str) -> str:
    match = re.search(rf"^{name}:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else ""


packages = []
for cabal in cabal_files:
    text = cabal.read_text(encoding="utf-8")
    packages.append(
        {
            "name": field(text, "name"),
            "synopsis": field(text, "synopsis"),
            "directory": cabal.parent.name,
            "text": text,
        }
    )

internal = {package["name"] for package in packages}

lines = []
for package in sorted(packages, key=lambda p: p["name"]):
    depends = set()
    for block in re.findall(
        r"^\s*build-depends:(.*?)(?=^\s*\S+:|\Z)", package["text"], re.MULTILINE | re.DOTALL
    ):
        for entry in block.split(","):
            token = entry.strip().split()
            if token and token[0] in internal:
                depends.add(token[0])
    depends.discard(package["name"])
    if depends:
        for target in sorted(depends):
            lines.append(f"{package['name']} --> {target}")
    else:
        lines.append(package["name"])

graph = "\n".join(lines)

dependency_out.write_text(
    "# Dependency Graph\n"
    "\n"
    "<!-- AUTOGENERATED: scripts/context/generate-dependency-map.sh -->\n"
    "\n"
    "각 패키지의 `.cabal` build-depends에서 추출한 내부 의존입니다.\n"
    "\n"
    "```text\n"
    f"{graph}\n"
    "```\n"
    "\n"
    "허용된 방향은 `ARCHITECTURE.md`가 정의하고 `scripts/quality/architecture-check.sh`가 검사합니다.\n"
    "이 파일을 직접 수정하지 마십시오.\n",
    encoding="utf-8",
)

rows = "\n".join(
    f"| {package['name']} | `src/{package['directory']}/README.md` | {package['synopsis']} |"
    for package in sorted(packages, key=lambda p: p["name"])
)

service_out.write_text(
    "# Service Map\n"
    "\n"
    "<!-- AUTOGENERATED: scripts/context/generate-dependency-map.sh -->\n"
    "\n"
    "| 패키지 | 지역 컨텍스트 | 책임 |\n"
    "|---|---|---|\n"
    f"{rows}\n"
    "\n"
    "책임 설명은 각 패키지 cabal 파일의 synopsis에서 가져옵니다.\n"
    "이 파일을 직접 수정하지 마십시오.\n",
    encoding="utf-8",
)
PY

if [[ "${1:-}" == "--check" ]]; then
  failed=0
  if ! cmp -s "$dependency_temporary" "$dependency_target"; then
    printf '생성 문서가 오래되었습니다: %s\n' "$dependency_target" >&2
    failed=1
  fi
  if ! cmp -s "$service_temporary" "$service_target"; then
    printf '생성 문서가 오래되었습니다: %s\n' "$service_target" >&2
    failed=1
  fi
  [[ "$failed" -eq 0 ]] || exit 1
  printf '의존성과 패키지 지도 최신 상태 확인\n'
else
  cp "$dependency_temporary" "$dependency_target"
  cp "$service_temporary" "$service_target"
  printf '생성 완료: %s, %s\n' "$dependency_target" "$service_target"
fi
