#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
target="$repo_root/docs/generated/db-schema.md"
temporary="$(mktemp)"
trap 'rm -f "$temporary"' EXIT

# 원본은 store가 소유하는 스키마 파일 하나입니다.
# Haskell 코드는 같은 파일을 컴파일 시점에 임베드하므로 사본이 존재하지 않습니다.
python3 - "$repo_root" "$temporary" <<'PY'
import sys
from pathlib import Path

root = Path(sys.argv[1])
out = Path(sys.argv[2])
source = root / "src/store/schema/schema.sql"

if not source.exists():
    print(f"스키마 원본이 없습니다: {source}", file=sys.stderr)
    raise SystemExit(1)

body = source.read_text(encoding="utf-8").rstrip("\n")

out.write_text(
    "# Database Schema\n"
    "\n"
    "<!-- AUTOGENERATED: scripts/context/generate-db-schema.sh -->\n"
    "\n"
    "원본: `src/store/schema/schema.sql`\n"
    "\n"
    "```sql\n"
    f"{body}\n"
    "```\n"
    "\n"
    "필드의 비즈니스 의미, 분류와 보존 정책은 `docs/contracts/data/TODO-STORE-v1.md`에 있습니다.\n"
    "이 파일을 직접 수정하지 마십시오.\n",
    encoding="utf-8",
)
PY

if [[ "${1:-}" == "--check" ]]; then
  if ! cmp -s "$temporary" "$target"; then
    printf '생성 문서가 오래되었습니다: %s\n' "$target" >&2
    exit 1
  fi
  printf 'DB 스키마 생성 문서 최신 상태 확인\n'
else
  cp "$temporary" "$target"
  printf '생성 완료: %s\n' "$target"
fi
