#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

required_paths=(
  AGENTS.md
  CLAUDE.md
  ARCHITECTURE.md
  README.md
  cabal.project
  docs/ai/INDEX.md
  docs/ai/CONTEXT_POLICY.md
  docs/ai/CONTEXT_LIFECYCLE.md
  docs/ai/OWNERSHIP.md
  docs/ai/WORKFLOW.md
  docs/ai/IMPACT_ANALYSIS.md
  docs/ai/DEFINITION_OF_DONE.md
  docs/ai/AUTHORITY.md
  docs/ai/RISK_LEVELS.md
  docs/product/INDEX.md
  docs/domain/INDEX.md
  docs/decisions/INDEX.md
  docs/contracts/INDEX.md
  docs/incidents/INDEX.md
  docs/tech-debt/INDEX.md
  docs/plans/active
  docs/plans/completed
  docs/generated/db-schema.md
  docs/generated/api-index.md
  docs/generated/route-map.md
  docs/generated/dependency-graph.md
  docs/generated/service-map.md
  src/store/schema/schema.sql
  src/api/src/Todo/Api/Routes.hs
)

failed=0
for path in "${required_paths[@]}"; do
  if [[ ! -e "$path" ]]; then
    printf '필수 컨텍스트가 없습니다: %s\n' "$path" >&2
    failed=1
  fi
done

for package in src/*; do
  [[ -d "$package" ]] || continue
  for required in AGENTS.md CLAUDE.md README.md docs/invariants.md docs/architecture.md docs/failure-modes.md src tests; do
    if [[ ! -e "$package/$required" ]]; then
      printf '패키지 컨텍스트가 없습니다: %s/%s\n' "$package" "$required" >&2
      failed=1
    fi
  done
  if ! compgen -G "$package/*.cabal" >/dev/null; then
    printf 'cabal 파일이 없습니다: %s\n' "$package" >&2
    failed=1
  fi
done

if [[ "$failed" -ne 0 ]]; then
  exit 1
fi

./scripts/context/check-broken-links.sh
./scripts/context/detect-stale-docs.sh

# 미해결 표식 검사입니다.
# 이 제품의 이름 자체가 Todo이므로 TODO-API-v1 같은 식별자와 표식을 구분해야 합니다.
# 앞뒤에 하이픈이나 밑줄이 붙은 경우는 식별자로 보고 제외합니다.
marker_pattern='(^|[^[:alnum:]_-])(TODO|TBD)([^[:alnum:]_-]|$)'
if grep -rEnq "$marker_pattern" docs/ai docs/product docs/domain docs/contracts; then
  printf 'Canonical Context에 해결되지 않은 TODO 또는 TBD가 있습니다.\n' >&2
  grep -rEn "$marker_pattern" docs/ai docs/product docs/domain docs/contracts >&2
  exit 1
fi

python3 - "$repo_root" <<'PY'
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

root = Path(sys.argv[1])
errors: list[str] = []

# 지도 파일은 지식을 복제하지 않고 안내만 합니다. 크기 제한이 그 규칙을 강제합니다.
size_limits = {
    root / "AGENTS.md": 100,
    root / "CLAUDE.md": 60,
}
for package_file in (root / "src").glob("*/AGENTS.md"):
    size_limits[package_file] = 80
for package_file in (root / "src").glob("*/CLAUDE.md"):
    size_limits[package_file] = 60

for path, limit in size_limits.items():
    line_count = len(path.read_text(encoding="utf-8").splitlines())
    if line_count > limit:
        errors.append(f"{path.relative_to(root)}: 지도 파일이 {line_count}줄이며 제한 {limit}줄을 넘음")

indexes = (
    (root / "docs/decisions", "ADR-[0-9][0-9][0-9][0-9]-*.md"),
    (root / "docs/incidents", "INC-*.md"),
)
for directory, pattern in indexes:
    index_text = (directory / "INDEX.md").read_text(encoding="utf-8")
    for document in directory.glob(pattern):
        if document.name not in index_text:
            errors.append(f"{document.relative_to(root)}: INDEX.md에 등록되지 않은 문서")

for generated in (root / "docs/generated").glob("*.md"):
    if "AUTOGENERATED:" not in generated.read_text(encoding="utf-8"):
        errors.append(f"{generated.relative_to(root)}: 생성 문서 표식 누락")

# 게시된 계약은 계약 지도에 등록되어 있어야 합니다.
contract_index = (root / "docs/contracts/INDEX.md").read_text(encoding="utf-8")
for area in ("api", "data", "events"):
    for contract in (root / "docs/contracts" / area).glob("*.md"):
        if contract.name in {"README.md", "CONTRACT-TEMPLATE.md"}:
            continue
        if contract.name not in contract_index:
            errors.append(f"{contract.relative_to(root)}: 계약 지도에 등록되지 않은 계약")

expiry = re.compile(r"(?:Expires|만료일)\s*:\s*(\d{4}-\d{2}-\d{2})", re.IGNORECASE)
for document in root.rglob("*.md"):
    if ".git" in document.parts or "dist-newstyle" in document.parts:
        continue
    for value in expiry.findall(document.read_text(encoding="utf-8")):
        if date.fromisoformat(value) < date.today():
            errors.append(f"{document.relative_to(root)}: 만료된 임시 예외 {value}")

if errors:
    print("컨텍스트 정책 위반을 발견했습니다:", file=sys.stderr)
    for error in errors:
        print(f"- {error}", file=sys.stderr)
    raise SystemExit(1)

print("컨텍스트 지도 크기, 인덱스와 만료 정책 검사 통과")
PY

printf '컨텍스트 무결성 검사 통과\n'
